CREATE TABLE IF NOT EXISTS fenrun_xp (
  identifier VARCHAR(64) PRIMARY KEY,
  xp INT NOT NULL DEFAULT 0 CHECK (xp >= 0),
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
